# Generated by Django 5.0.4 on 2024-04-14 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='booking_date',
            field=models.DateField(default=datetime.date(2024, 4, 14)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
