# Generated by Django 5.0.4 on 2024-04-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0002_alter_bookingtable_booking_date_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
